"""initial migration

Revision ID: 163e8026d053
Revises: 
Create Date: 2022-05-22 01:11:30.065715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '163e8026d053'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comment_table_name', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('post_table_name', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_unique_constraint(None, 'tag_table_name', ['title'])
    op.alter_column('user_table_name', 'username',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_index(op.f('ix_user_table_name_username'), 'user_table_name', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_table_name_username'), table_name='user_table_name')
    op.alter_column('user_table_name', 'username',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint(None, 'tag_table_name', type_='unique')
    op.alter_column('post_table_name', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('comment_table_name', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
