"""empty message

Revision ID: 795b912e3b3b
Revises: ee9efab63745
Create Date: 2022-06-25 00:01:07.769531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '795b912e3b3b'
down_revision = 'ee9efab63745'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_table_name', sa.Column('youtube_id', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post_table_name', 'youtube_id')
    # ### end Alembic commands ###
